---

- name: Install nginx config file
  template:
    src: files/nginx.j2
    dest: /usr/local/etc/nginx/nginx.conf

- name: Enable and run nginx
  service:
    name: nginx
    enabled: yes
    state: started
