---
# Setup SSL Certs with Let's Encrypt after installing nextcloud

# General vars including FreeBSD specific ansible tweaks
- hosts: test
  remote_user: root
  become: yes
  become_method: su
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/local/bin/python3.8"
  # vars_files:
  #   # - secrets/custom_pkg.yml
  #   # - secrets/dbcred.yml
  #   - secrets/server.yml
  vars_prompt:
    - name: server_name
      prompt: Please enter the server name
      private: no


 
  roles:
    - ssl
