---
- name: Setup pkg directory
  file: path=/usr/local/etc/pkg/repos state=directory

- name: Disable 'quarterly' pkg repo, use 'latest' instead
  copy:
    src: files/{{item}}
    dest: /usr/local/etc/pkg/repos/{{item}}
  with_items:
    - FreeBSD.conf
    - FreeBSD-latest.conf

- name: Install required packages
  pkgng: name={{item}} state=present
  with_items:
    - nextcloud-php72
    - mysql56-server
    - nginx
    - redis
    - php72-pecl-redis

- name: Install optional packages for nextcloud
  pkgng: name={{item}} state=present
  with_items:
    - nextcloud-calendar-php72
    - nextcloud-contacts-php72
    - nextcloud-mail-php72
    - nextcloud-notes-php72
    - nextcloud-passman-php72
    - nextcloud-tasks-php72
    - nextcloud-twofactor_totp-php72
    - nextcloud-twofactor_u2f-php72
  tags: optional

