---
#- name: Setup pkg directories
  #file:
   # path: /usr/local/etc/pkg/{{item}}
  #  state: directory
 # with_items:
    #- repos
    #- keys

#- name: Disable 'quarterly' pkg repo
 # copy:
  #  src: files/{{item}}
   # dest: /usr/local/etc/pkg/repos/{{item}}
  #with_items:
   # - FreeBSD.conf

#- name: Configure custom pkg repo
 # template:
  #  src: files/custom_pkg.j2
   # dest: /usr/local/etc/pkg/repos/custom.conf

#- name: Provide public key for custom pkg repo
 # copy:
  #  src: secrets/{{custom_repo.key}}
   # dest: /usr/local/etc/pkg/keys/{{custom_repo.key}}

- name: Install required packages
  pkgng: name={{item}} state=present
  with_items:
    - nextcloud-php80
    - postgresql14-server
    - postgresql14-client
    - nginx
    - python
    - py38-certbot
    - py38-certbot-nginx
    - py38-pip
    - bash
    - nano   
    
    # - redis
    # - php74-pecl-redis

- name: Install optional packages for nextcloud
  pkgng: name={{item}} state=present
  with_items:
    - nextcloud-calendar-php80
    - nextcloud-contacts-php80
    - nextcloud-mail-php80
    - nextcloud-notes-php80
    - nextcloud-passman-php80
    - nextcloud-tasks-php80
    - nextcloud-twofactor_totp-php80
    - nextcloud-twofactor_u2f-php80
  tags: optional
