#!/bin/sh

set -e

ROOTPASSWORD=$1
NCUSERNAME=$2
NCUSERPASSWORD=$3

psql -U postgres << EOF
ALTER USER postgres WITH PASSWORD '$ROOTPASSWORD';
CREATE USER '$NCUSERNAME' WITH PASSWORD '$NCUSERPASSWORD';
CREATE DATABASE nextcloud ENCODING 'UNICODE' OWNER '$NCUSERNAME';
EOF

touch /var/db/postgres/PSQL_NEXTCLOUD_ADMIN_DONE

